### ISSUE TITLE
`wordHighlighter`: Invoking deltaDecorations recursively could lead to leaking decorations.

### ISSUE THREAD

**Issue by vscodenpa** [vscodenpa/testissues#105]
```javascript
Error: Invoking deltaDecorations recursively could lead to leaking decorations.
at rn.deltaDecorations in src/vs/editor/common/model/textModel.ts:1620:23
at sn.deltaDecorations in src/vs/editor/browser/widget/codeEditorWidget.ts:1289:32
at O._removeDecorations in src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts:306:38
at O._stopAll in src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts:313:8
at O._onPositionChanged in src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts:344:9
at <anonymous> in src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts:224:9
at p.invoke in src/vs/base/common/event.ts:575:17
at l.deliver in src/vs/base/common/event.ts:779:22
at o.fire in src/vs/base/common/event.ts:740:24
at <anonymous> in src/vs/editor/browser/widget/codeEditorWidget.ts:1635:38
at p.invoke in src/vs/base/common/event.ts:575:17
at r.deliver in src/vs/base/common/event.ts:779:22
at o.fire in src/vs/base/common/event.ts:740:24
at _emitOutgoingEvents in src/vs/editor/common/viewModelEventDispatcher.ts:64:18
at _.endEmitViewEvents in src/vs/editor/common/viewModelEventDispatcher.ts:109:8
at _.emitSingleViewEvent in src/vs/editor/common/viewModelEventDispatcher.ts:117:9
at <anonymous> in src/vs/editor/common/viewModel/viewModelImpl.ts:462:26
at p.invoke in src/vs/base/common/event.ts:575:17
at r.deliver in src/vs/base/common/event.ts:779:22
at o.fire in src/vs/base/common/event.ts:740:24
at ne.endDeferredEmit in src/vs/editor/common/model/textModel.ts:2339:18
at rn.deltaDecorations in src/vs/editor/common/model/textModel.ts:1625:33
at sn.deltaDecorations in src/vs/editor/browser/widget/codeEditorWidget.ts:1289:32
at O._removeDecorations in src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts:306:38
at O._stopAll in src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts:313:8
at <anonymous> in src/vs/editor/contrib/wordHighlighter/browser/wordHighlighter.ts:227:9
at p.invoke in src/vs/base/common/event.ts:575:17
at l.deliver in src/vs/base/common/event.ts:779:22
at o.fire in src/vs/base/common/event.ts:740:24
at <anonymous> in src/vs/editor/browser/widget/codeEditorWidget.ts:1661:36
at p.invoke in src/vs/base/common/event.ts:575:17
at r.deliver in src/vs/base/common/event.ts:779:22
at o.fire in src/vs/base/common/event.ts:740:24
at _emitOutgoingEvents in src/vs/editor/common/viewModelEventDispatcher.ts:64:18
at _.endEmitViewEvents in src/vs/editor/common/viewModelEventDispatcher.ts:109:8
at v._withViewEventsCollector in src/vs/editor/common/viewModel/viewModelImpl.ts:1055:26
at v._executeCursorEdit in src/vs/editor/common/viewModel/viewModelImpl.ts:992:8
at v.type in src/vs/editor/common/viewModel/viewModelImpl.ts:1004:8
at sn._type in src/vs/editor/browser/widget/codeEditorWidget.ts:1142:29
at sn.trigger in src/vs/editor/browser/widget/codeEditorWidget.ts:1075:10
at T.runCommand in src/vs/editor/browser/coreCommands.ts:1892:10
at handler in src/vs/editor/browser/editorExtensions.ts:121:38
at I.handler in src/vs/platform/commands/common/commands.ts:90:12
at b.invokeFunction in src/vs/platform/instantiation/common/instantiationService.ts:61:11
at b._tryExecuteCommand (vscode-file://vscode-app/
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=9c29becfad5f68270b9b23efeafb147722c5feba&bH=8d3592f0-0239-4676-7888-0bfb09973618)

**Comment by vscodenpa** [comment]
confidence for label snippets: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee alexdima: 0.65. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label snippets: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee alexdima: 0.65. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label snippets: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee alexdima: 0.65. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label snippets: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee alexdima: 0.65. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label snippets: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee alexdima: 0.65. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label snippets: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee alexdima: 0.65. does not meet threshold
