### ISSUE TITLE
`contentHover`: Invoking deltaDecorations recursively could lead to leaking decorations.

### ISSUE THREAD

**Issue by vscodenpa** [vscodenpa/testissues#107]
```javascript
Error: Invoking deltaDecorations recursively could lead to leaking decorations.
at rn.deltaDecorations in src/vs/editor/common/model/textModel.ts:1620:23
at sn.deltaDecorations in src/vs/editor/browser/widget/codeEditorWidget.ts:1289:32
at c.deltaDecorations in src/vs/editor/contrib/hover/browser/contentHover.ts:294:24
at <anonymous> in src/vs/editor/contrib/hover/browser/contentHover.ts:246:39
at <anonymous> in src/vs/base/common/lifecycle.ts:170:4
at Object.dispose in src/vs/base/common/functional.ts:17:15
at i in src/vs/base/common/lifecycle.ts:139:8
at l.clear in src/vs/base/common/lifecycle.ts:214:4
at l.dispose in src/vs/base/common/lifecycle.ts:199:8
at so._setVisibleData in src/vs/editor/contrib/hover/browser/contentHover.ts:390:34
at so.hide in src/vs/editor/contrib/hover/browser/contentHover.ts:443:9
at ro.hide in src/vs/editor/contrib/hover/browser/contentHover.ts:167:16
at mo._hideWidgets in src/vs/editor/contrib/hover/browser/hover.ts:206:24
at mo._onKeyDown in src/vs/editor/contrib/hover/browser/hover.ts:195:9
at <anonymous> in src/vs/editor/contrib/hover/browser/hover.ts:82:74
at p.invoke in src/vs/base/common/event.ts:575:17
at l.deliver in src/vs/base/common/event.ts:779:22
at o.fire in src/vs/base/common/event.ts:740:24
at <anonymous> in src/vs/editor/browser/widget/codeEditorWidget.ts:1651:40
at p.invoke in src/vs/base/common/event.ts:575:17
at r.deliver in src/vs/base/common/event.ts:779:22
at o.fire in src/vs/base/common/event.ts:740:24
at _emitOutgoingEvents in src/vs/editor/common/viewModelEventDispatcher.ts:64:18
at _.emitOutgoingEvent in src/vs/editor/common/viewModelEventDispatcher.ts:39:8
at <anonymous> in src/vs/editor/common/viewModel/viewModelImpl.ts:463:26
at p.invoke in src/vs/base/common/event.ts:575:17
at r.deliver in src/vs/base/common/event.ts:779:22
at o.fire in src/vs/base/common/event.ts:740:24
at ne.endDeferredEmit in src/vs/editor/common/model/textModel.ts:2339:18
at rn.deltaDecorations in src/vs/editor/common/model/textModel.ts:1625:33
at sn.deltaDecorations in src/vs/editor/browser/widget/codeEditorWidget.ts:1289:32
at On.removeLinkDecorations in src/vs/editor/contrib/gotoSymbol/browser/link/goToDefinitionAtPosition.ts:276:39
at <anonymous> in src/vs/editor/contrib/gotoSymbol/browser/link/goToDefinitionAtPosition.ts:76:9
at p.invoke in src/vs/base/common/event.ts:575:17
at r.deliver in src/vs/base/common/event.ts:779:22
at o.fire in src/vs/base/common/event.ts:740:24
at b._onEditorKeyDown in src/vs/editor/contrib/gotoSymbol/browser/link/clickLinkGesture.ts:193:19
at <anonymous> in src/vs/editor/contrib/gotoSymbol/browser/link/clickLinkGesture.ts:141:69
at p.invoke in src/vs/base/common/event.ts:575:17
at l.deliver in src/vs/base/common/event.ts:779:22
at o.fire in src/vs/base/common/event.ts:740:24
at t.re.onKeyDown in src/vs/editor/browser/widget/codeEditorWidget.ts:1753:58
at t.emitKeyDown in src/vs/editor/browser/view/viewUserInputEvents.ts:37:9
at R.emitKeyDown in src/vs/editor/browser/view/viewController.ts:293:24
at <anonymous> in src/vs/editor/browser/controller/textAreaHandler.ts:284:25
at p.invoke in src/vs/base/common/event.ts:575:17
at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=9c29becfad5f68270b9b23efeafb147722c5feba&bH=5d122020-88bc-8ab5-df2c-b48e8588c6f4)

**Comment by vscodenpa** [comment]
confidence for label api: 0.4. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee aeschli: 0.7. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label api: 0.4. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee aeschli: 0.7. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label api: 0.4. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee aeschli: 0.7. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label api: 0.4. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee aeschli: 0.7. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label api: 0.4. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee aeschli: 0.7. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label api: 0.4. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee aeschli: 0.7. does not meet threshold
