### ISSUE TITLE
`searchModel`: Invoking deltaDecorations recursively could lead to leaking decorations.

### ISSUE THREAD

**Issue by vscodenpa** [vscodenpa/testissues#109]
```javascript
Error: Invoking deltaDecorations recursively could lead to leaking decorations.
at rn.deltaDecorations in src/vs/editor/common/model/textModel.ts:1620:23
at ua.removeHighlightRange in src/vs/workbench/contrib/search/common/searchModel.ts:1225:16
at <anonymous> in src/vs/workbench/contrib/search/common/searchModel.ts:1255:10
at p.invoke in src/vs/base/common/event.ts:575:17
at r.deliver in src/vs/base/common/event.ts:779:22
at o.fire in src/vs/base/common/event.ts:740:24
at ne.endDeferredEmit in src/vs/editor/common/model/textModel.ts:2339:18
at rn.deltaDecorations in src/vs/editor/common/model/textModel.ts:1625:33
at ua.removeHighlightRange in src/vs/workbench/contrib/search/common/searchModel.ts:1225:16
at N.set query [as query] in src/vs/workbench/contrib/search/common/searchModel.ts:749:35
at L.search in out/vs/workbench/workbench.desktop.main.js:2128:15341
at _l.doSearch in src/vs/workbench/contrib/search/browser/searchView.ts:1585:25
at <anonymous> in src/vs/workbench/contrib/search/browser/searchView.ts:1428:21
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=9c29becfad5f68270b9b23efeafb147722c5feba&bH=d06cfc68-d899-eed1-cfb3-a0253e061b67)

**Comment by vscodenpa** [comment]
confidence for label search: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee roblourens: 0.65. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label search: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee roblourens: 0.65. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label search: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee roblourens: 0.65. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label search: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee roblourens: 0.65. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label search: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee roblourens: 0.65. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label search: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee roblourens: 0.65. does not meet threshold
