### ISSUE TITLE
Can not update extensions due to "Error: Server returned 404"

### ISSUE THREAD

**Issue by vscodenpa** [vscodenpa/testissues#3]
- VS Code Version: 1.68.0-insider
- OS Version: Windows 10 21H2

Steps to Reproduce:

1. Have rust-analyzer 0.2.853 installed from the marketplace
2. Observe that your extensions are out of date.
3. Try to use the "Check for Extension Updates" option
4. Receive notification alert "Error: Server returned 404", no extensions receive updates.

Uninstalling rust-analyzer 0.2.853 resolved this for me.

Expectations:

1. Notification Alert would have shown which extension it was. I only found out via the Developer Tools Console.
2. Other extensions would have updated fine regardless of this error caused by one extension.

Developer Tools Console output:

```
request.ts:46 
 GET https://rust-lang.gallerycdn.vsassets.io/extensions/rust-lang/rust-analyzer/0.2.853/1639376535349/Microsoft.VisualStudio.Code.Manifest 404
request.ts:46 
 GET https://rust-lang.gallerycdn.vsassets.io/extensions/rust-lang/rust-analyzer/0.2.853/1639376535349/Microsoft.VisualStudio.Code.Manifest 404
notificationsAlerts.ts:40 Error: Server returned 404
    at C (request.ts:49:9)
    at J.getManifestFromRawExtensionVersion (extensionGalleryService.ts:1023:16)
    at async J.getEngine (extensionGalleryService.ts:1128:21)
    at async J.isValidVersion (extensionGalleryService.ts:671:19)
    at async J.toGalleryExtensionWithCriteria (extensionGalleryService.ts:868:8)
    at async J.queryGalleryExtensions (extensionGalleryService.ts:809:22)
    at async J.getExtensions (extensionGalleryService.ts:618:26)
    at async Ms.checkForUpdates (extensionsWorkbenchService.ts:1076:30)
    at async Object.run (extensions.contribution.ts:584:5)
    at async k.runAction (actions.ts:190:3)
    at async k.run (actions.ts:181:4)
```

**Comment by vscodenpa** [comment]
confidence for label extensions: 0.85. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee sandy081: 0.75. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label extensions: 0.85. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee sandy081: 0.75. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label extensions: 0.85. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee sandy081: 0.75. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label extensions: 0.85. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee sandy081: 0.75. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label extensions: 0.85. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee sandy081: 0.75. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label extensions: 0.85. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee sandy081: 0.75. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label extensions: 0.85. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee sandy081: 0.75. does meet threshold
