### ISSUE TITLE
Could not parse color as CSS color

### ISSUE THREAD

**Issue by vscodenpa** [vscodenpa/testissues#426]
```javascript
Error: Could not parse color as CSS color
at f.updateTitleBarOverlay in src/vs/platform/native/electron-main/nativeHostMainService.ts:222:15
at Object.call in src/vs/base/parts/ipc/common/ipc.ts:1089:20
at a.onPromise in src/vs/base/parts/ipc/common/ipc.ts:381:22
at a.onRawMessage in src/vs/base/parts/ipc/common/ipc.ts:356:17
at <anonymous> in src/vs/base/parts/ipc/common/ipc.ts:300:63
at h.invoke in src/vs/base/common/event.ts:575:17
at C.deliver in src/vs/base/common/event.ts:779:22
at p.fire in src/vs/base/common/event.ts:740:24
at <anonymous> in src/vs/base/common/event.ts:90:84
at h.invoke in src/vs/base/common/event.ts:575:17
at C.deliver in src/vs/base/common/event.ts:779:22
at p.fire in src/vs/base/common/event.ts:740:24
at <anonymous> in src/vs/base/common/event.ts:111:97
at h.invoke in src/vs/base/common/event.ts:575:17
at C.deliver in src/vs/base/common/event.ts:779:22
at p.fire in src/vs/base/common/event.ts:740:24
at T in src/vs/base/common/event.ts:382:41
at IpcMainImpl.g in src/vs/base/parts/ipc/electron-main/ipcMain.ts:29:5
at IpcMainImpl.emit (node:events:390:28)
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:169:10120)
at EventEmitter.emit (node:events:390:28)
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=17c75e11805103026b943c8dc4d50a35f245f76f&bH=2df6fae9-6c18-789f-a5d7-cd22d761471d)

**Comment by vscodenpa** [comment]
confidence for label grammar: 0.4. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee aeschli: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label grammar: 0.4. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee aeschli: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label grammar: 0.4. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee aeschli: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label grammar: 0.4. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee aeschli: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label grammar: 0.4. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee aeschli: 0.8. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label grammar: 0.4. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee aeschli: 0.8. does meet threshold
