### ISSUE TITLE
TypeScript language server exited with error. Error message is: Channel closed

### ISSUE THREAD

**Issue by vscodenpa** [vscodenpa/testissues#64]
Issue Type: <b>Bug</b>

Environment: Remote dev container using Remote - Containers extension v0.234.0

Problem: The Typescript language server constantly dies and restarts. Here is the log output showing such event:

[2022-05-14 22:33:08.821] [renderer2] [error] {"isTrusted":true}
[2022-05-14 22:33:08.821] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2022-05-14 22:33:08.822] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] resolving connection...
[2022-05-14 22:33:08.822] [renderer2] [info] Invoking resolveAuthority(dev-container)
[2022-05-14 22:33:08.823] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
[2022-05-14 22:33:08.823] [renderer2] [error] {"isTrusted":true}
[2022-05-14 22:33:08.823] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2022-05-14 22:33:08.823] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] resolving connection...
[2022-05-14 22:33:09.022] [renderer2] [info] resolveAuthority(dev-container) returned '127.0.0.1:58075' after 200 ms
[2022-05-14 22:33:09.023] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] connecting to 127.0.0.1:58075...
[2022-05-14 22:33:09.023] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] connecting to 127.0.0.1:58075...
[2022-05-14 22:33:09.238] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] reconnected!
[2022-05-14 22:33:09.455] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] reconnected!
[2022-05-14 22:44:35.321] [renderer2] [error] <syntax> TypeScript Server Error (4.6.3)
Debug Failure.
Error: Debug Failure.
    at getAutoImportSymbolFromCompletionEntryData (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:132025:66)
    at getSymbolCompletionFromEntryId (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:130247:34)
    at Object.getCompletionEntryDetails (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:130295:36)
    at Object.getCompletionEntryDetails (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:161877:35)
    at /vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:173451:57
    at Object.mapDefined (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:605:30)
    at IpcIOSession.Session.getCompletionEntryDetails (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:173449:33)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:172271:61)
    at /vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:174069:88
    at IpcIOSession.Session.executeWithRequestId (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:174060:28)
    at IpcIOSession.Session.executeCommand (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:174069:33)
    at IpcIOSession.Session.onMessage (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:174095:35)
    at process.<anonymous> (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:176730:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21): Error: <syntax> TypeScript Server Error (4.6.3)
Debug Failure.
Error: Debug Failure.
    at getAutoImportSymbolFromCompletionEntryData (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:132025:66)
    at getSymbolCompletionFromEntryId (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:130247:34)
    at Object.getCompletionEntryDetails (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:130295:36)
    at Object.getCompletionEntryDetails (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:161877:35)
    at /vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:173451:57
    at Object.mapDefined (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:605:30)
    at IpcIOSession.Session.getCompletionEntryDetails (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:173449:33)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:172271:61)
    at /vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:174069:88
    at IpcIOSession.Session.executeWithRequestId (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:174060:28)
    at IpcIOSession.Session.executeCommand (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:174069:33)
    at IpcIOSession.Session.onMessage (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:174095:35)
    at process.<anonymous> (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/extensions/node_modules/typescript/lib/tsserver.js:176730:31)
    at process.emit (node:events:390:28)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
	at o._executeContributedCommand (/vscode/vscode-server/bin/linux-arm64/57fd6d0195bb9b9d1b49f6da5db789060795de47/out/vs/workbench/api/node/extensionHostProcess.js:83:31519)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-05-14 23:09:48.634] [renderer2] [warning] {}
[2022-05-14 23:36:45.298] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
[2022-05-14 23:36:45.299] [renderer2] [error] {"isTrusted":true}
[2022-05-14 23:36:45.299] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2022-05-14 23:36:45.299] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] resolving connection...
[2022-05-14 23:36:45.299] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] connecting to 127.0.0.1:58075...
[2022-05-14 23:36:45.299] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
[2022-05-14 23:36:45.300] [renderer2] [error] {"isTrusted":true}
[2022-05-14 23:36:45.300] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2022-05-14 23:36:45.301] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] resolving connection...
[2022-05-14 23:36:45.301] [renderer2] [info] Invoking resolveAuthority(dev-container)
[2022-05-14 23:36:45.559] [renderer2] [info] resolveAuthority(dev-container) returned '127.0.0.1:58075' after 259 ms
[2022-05-14 23:36:45.559] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] connecting to 127.0.0.1:58075...
[2022-05-14 23:36:45.776] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] reconnected!
[2022-05-14 23:36:45.993] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] reconnected!
[2022-05-14 23:37:44.910] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
[2022-05-14 23:37:44.910] [renderer2] [error] {"isTrusted":true}
[2022-05-14 23:37:44.910] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2022-05-14 23:37:44.910] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] resolving connection...
[2022-05-14 23:37:44.910] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] connecting to 127.0.0.1:58075...
[2022-05-14 23:37:44.910] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
[2022-05-14 23:37:44.910] [renderer2] [error] {"isTrusted":true}
[2022-05-14 23:37:44.911] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2022-05-14 23:37:44.912] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] resolving connection...
[2022-05-14 23:37:44.913] [renderer2] [info] Invoking resolveAuthority(dev-container)
[2022-05-14 23:37:45.280] [renderer2] [info] resolveAuthority(dev-container) returned '127.0.0.1:58075' after 369 ms
[2022-05-14 23:37:45.280] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] connecting to 127.0.0.1:58075...
[2022-05-14 23:37:45.388] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] reconnected!
[2022-05-14 23:37:45.611] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] reconnected!
[2022-05-15 11:58:58.172] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
[2022-05-15 11:58:58.172] [renderer2] [error] {"isTrusted":true}
[2022-05-15 11:58:58.172] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2022-05-15 11:58:58.172] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] resolving connection...
[2022-05-15 11:58:58.173] [renderer2] [info] Invoking resolveAuthority(dev-container)
[2022-05-15 11:58:58.173] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] received socket close event (wasClean: false, code: 1006, reason: ).
[2022-05-15 11:58:58.173] [renderer2] [error] {"isTrusted":true}
[2022-05-15 11:58:58.173] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
[2022-05-15 11:58:58.173] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] resolving connection...
[2022-05-15 11:58:58.308] [renderer2] [info] resolveAuthority(dev-container) returned '127.0.0.1:58075' after 135 ms
[2022-05-15 11:58:58.308] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] connecting to 127.0.0.1:58075...
[2022-05-15 11:58:58.308] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] connecting to 127.0.0.1:58075...
[2022-05-15 11:58:58.849] [renderer2] [info] [remote-connection][Management   ][55ff6…][reconnect] reconnected!
[2022-05-15 11:58:59.096] [renderer2] [info] [remote-connection][ExtensionHost][aad19…][reconnect] reconnected!

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:10:15.217Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No
Remote OS version: Linux arm64 5.10.76-linuxkit
Remote OS version: Linux arm64 5.10.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.02GB free)|
|Process Argv|--crash-reporter-id d1ec207a-95c7-4466-9d2b-b744eb42f766|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: inrev-dev|
|OS|Linux arm64 5.10.76-linuxkit|
|CPUs|unknown (5 x 0)|
|Memory (System)|1.94GB (0.39GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: inrev-dev|
|OS|Linux arm64 5.10.76-linuxkit|
|CPUs|unknown (5 x 0)|
|Memory (System)|1.94GB (0.39GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.234.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
testflightcf:30433671
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaac:30438847
vsclangdf:30486550

```

</details>

**Comment by vscodenpa** [comment]
confidence for label javascript: 0.7. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee mjbvz: 0.95. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label javascript: 0.7. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee mjbvz: 0.95. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label javascript: 0.7. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee mjbvz: 0.95. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label javascript: 0.7. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee mjbvz: 0.95. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label javascript: 0.7. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee mjbvz: 0.95. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label javascript: 0.7. does meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee mjbvz: 0.95. does meet threshold
