### ISSUE TITLE
No SharedServer found.

### ISSUE THREAD

**Issue by vscodenpa** [vscodenpa/testissues#68]
```javascript
Error: No SharedServer found.
at assert in /home/ubuntu/.vscode-remote/extensions/utils/dist/src/utils/asserts/assert.js:12:1
at assertDefined in /home/ubuntu/.vscode-remote/extensions/utils/dist/src/utils/asserts/assertDefined.js:11:1
at VSCodeConnection.get sharedServer [as sharedServer] in /home/ubuntu/.vscode-remote/extensions/workspace/connection-hub/dist/src/connection/VSCodeConnection.js:169:1
at VSCodeConnection.<anonymous> in /home/ubuntu/.vscode-remote/extensions/workspace/connection-hub/dist/src/connection/VSCodeConnection.js:348:1
at Generator.next (<anonymous>)
at <anonymous> in /home/ubuntu/.vscode-remote/extensions/workspace/connection-hub/dist/src/connection/VSCodeConnection.js:17:1
at new Promise (<anonymous>)
at __webpack_modules__.10109.__awaiter in /home/ubuntu/.vscode-remote/extensions/workspace/connection-hub/dist/src/connection/VSCodeConnection.js:13:1
at <anonymous> in /home/ubuntu/.vscode-remote/extensions/workspace/connection-hub/dist/src/connection/VSCodeConnection.js:347:14
at PerformanceBlocks.<anonymous> in /home/ubuntu/.vscode-remote/extensions/performance/dist/src/PerformanceBlocks.js:112:1
at Generator.next (<anonymous>)
at <anonymous> in /home/ubuntu/.vscode-remote/extensions/performance/dist/src/PerformanceBlocks.js:8:1
at new Promise (<anonymous>)
at __webpack_modules__.87522.__awaiter in /home/ubuntu/.vscode-remote/extensions/performance/dist/src/PerformanceBlocks.js:4:1
at PerformanceBlocks.measure in /home/ubuntu/.vscode-remote/extensions/performance/dist/src/PerformanceBlocks.js:109:1
at Performance.<anonymous> in /home/ubuntu/.vscode-remote/extensions/performance/dist/src/Performance.js:92:1
at Generator.next (<anonymous>)
at <anonymous> in /home/ubuntu/.vscode-remote/extensions/performance/dist/src/Performance.js:8:1
at new Promise (<anonymous>)
at __webpack_modules__.24004.__awaiter in /home/ubuntu/.vscode-remote/extensions/performance/dist/src/Performance.js:4:1
at Performance.measure in /home/ubuntu/.vscode-remote/extensions/performance/dist/src/Performance.js:91:1
at VSCodeConnection.<anonymous> in /home/ubuntu/.vscode-remote/extensions/workspace/connection-hub/dist/src/connection/VSCodeConnection.js:344:1
at Generator.next (<anonymous>)
at <anonymous> in /home/ubuntu/.vscode-remote/extensions/workspace/connection-hub/dist/src/connection/VSCodeConnection.js:17:1
at new Promise (<anonymous>)
at __webpack_modules__.10109.__awaiter in /home/ubuntu/.vscode-remote/extensions/workspace/connection-hub/dist/src/connection/VSCodeConnection.js:13:1
at VSCodeConnection.openChannel in /home/ubuntu/.vscode-remote/extensions/workspace/connection-hub/dist/src/connection/VSCodeConnection.js:336:1
at VSCodeConnection.<anonymous> in /home/ubuntu/.vscode-remote/extensions/workspace/connection-hub/dist/src/connection/VSCodeConnection.js:157:1
at Generator.next (<anonymous>)
at fulfilled in /home/ubuntu/.vscode-remote/extensions/workspace/connection-hub/dist/src/connection/VSCodeConnection.js:14:43
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=da15b6fd3ef856477bf6f4fb29ba1b7af717770d&bH=2a6df754-061a-8868-ff51-aaecd371b618)

**Comment by vscodenpa** [comment]
confidence for label api: 0.3. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee bpasero: 0.5. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label api: 0.3. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee bpasero: 0.5. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label api: 0.3. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee bpasero: 0.5. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label api: 0.3. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee bpasero: 0.5. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label api: 0.3. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee bpasero: 0.5. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for label api: 0.3. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee bpasero: 0.5. does not meet threshold
