### ISSUE TITLE
spawn EBADF

### ISSUE THREAD

**Issue by vscodenpa** [vscodenpa/testissues#70]
```javascript
Error: spawn EBADF
at ChildProcess.spawn (node:internal/child_process:412:11)
at Object.spawn (node:child_process:718:9)
at spawn in extensions/git/src/git.ts:634:13
at spawn in extensions/git/src/git.ts:544:22
at stream in extensions/git/src/git.ts:892:19
at <anonymous> in extensions/git/src/repository.ts:1707:35
at new Promise (<anonymous>)
at <anonymous> in extensions/git/src/repository.ts:1696:11
at O.retryRun in extensions/git/src/repository.ts:1823:18
at O.run in extensions/git/src/repository.ts:1796:30
at O.checkIgnore in extensions/git/src/repository.ts:1695:15
at checkIgnore in extensions/git/src/decorationProvider.ts:65:20
at apply in extensions/git/src/decorators.ts:98:41
at listOnTimeout (node:internal/timers:557:17)
at processTimers (node:internal/timers:500:7)
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=da15b6fd3ef856477bf6f4fb29ba1b7af717770d&bH=2a9cc2f0-2c56-668d-adeb-e41d10b76ce2)

**Comment by vscodenpa** [comment]
confidence for label terminal: 0.6. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee Tyriar: 0.75. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label terminal: 0.6. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee Tyriar: 0.75. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label terminal: 0.6. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee Tyriar: 0.75. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label terminal: 0.6. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee Tyriar: 0.75. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label terminal: 0.6. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee Tyriar: 0.75. does meet threshold

**Comment by vscodenpa** [comment]
confidence for label terminal: 0.6. does not meet threshold

**Comment by vscodenpa** [comment]
confidence for assignee Tyriar: 0.75. does meet threshold
